### ISSUE TITLE
What's the meaning of T035?

### ISSUE THREAD

**Issue by VictorZXY** [cotr/PhysicsSimulator#2]
It occurs two compile errors...So I can't run my code and I don't konw how to clear these two errors...

**Comment by xfoxfu** [comment]
Detail needed.
At least, it runs good on my computer.

**Comment by VictorZXY** [comment]
So why is it on my computer?

**Comment by xfoxfu** [comment]
As I said, you should put the bin file of `T035` into your `Windows\System32` folder, or you cannot compile the solution.
Is there any trouble with your compile of `T035`? It is a pre-compile event handler, used to auto-increase the version.
And also, a compiled copy of `T035.exe` is attached.

**Comment by xfoxfu** [comment]
Due to my work today, `T035` can work on every clone of this repo currently. So this issue is closed.
